### ISSUE TITLE
Raspi 4 binary

### ISSUE THREAD

**Issue by citizenanalog** [cculianu/Fulcrum#101]
I'm attempting to run the 'Fulcrum-1.6.0-arm64-linux.tar.gz' binary on a raspi 4 and getting:

pi@raspberrypi:~/Fulcrum $ ./Fulcrum
bash: ./Fulcrum: cannot execute binary file: Exec format error

Should this work on a raspi 4?

**Comment by cculianu** [comment]
It needs to be a 64-bit OS.  If you are using the out-of-the-box Raspian -- that is a 32-bit OS.  Did you install Ubuntu 64-bit or some other 64-bit OS?

**Comment by citizenanalog** [comment]
Ah that's my problem. Yes using Raspbian 32bit. Thanks!

**Comment by cculianu** [comment]
Ok let me label this as "Raspian 32-Bit" so others see this...

Yeah maybe I should have made it clearer in the release -- Fulcrum requires a 64-bit OS because it really really REALLy wants to be able to -- in times of need -- address more than 3GB of memory ... even if it's just memory-mapped files from disk -- it REALLY wants 64-bit pointers, so it's requires a 64-bit OS.

**Comment by cculianu** [comment]
I highly recomment any of the Ubuntus for Raspberry Pi.  I really like what they have done -- it's an easy setup and it opens up the RPi to 64-bit apps....

**Comment by citizenanalog** [comment]
I had issues with Ubuntu on the Raspi CM4, it would boot the OS and lock up when any significant RAM was used.
