### ISSUE TITLE
Cannot connect to Fulcrum via Tor

### ISSUE THREAD

**Issue by DanielPX1** [cculianu/Fulcrum#118]
Hello,

I have successfully synced Fulcrum on raspberry pi 4 and trying to set up Tor hidden service to use for remote connections. Fulcrum works connecting on my local network specifing device IP and Port. However I am unable to connect via Tor, I don't know
how working config looks like, since it is very different from electrum config file I was using before.

I have set up following in my torrc config:
### Torrc
 ```sh
HiddenServiceDir /var/lib/tor/hidden_service_fulcrum/
HiddenServiceVersion 3
HiddenServicePort 50002 127.0.0.1:50002
 ```

and then printed my hostname using: 'sudo cat /var/lib/tor/hidden_service_fulcrum/hostname'
xyz.onion

My config file for fulcrum is set up like this:
### Fulcrum config
 ```sh
datadir = /path/to/db/
bitcoind = 127.0.0.1:8332
rpcuser = username
rpcpassword = password
cert = /path/
key = /path/
peering = false
ssl = 0.0.0.0:50002
tor_hostname=xyz.onion (copied from hostname)
tor_tcp_port = 50001
tor_ssl_port = 50002
 ```
- ports allowed for UFW

### NGINX
 ```sh
upstream fulcrum {
  server 127.0.0.1:50001;
}

server {
  listen 50002 ssl;
  proxy_pass fulcrum;
}
 ```

Trying to connect with my wallet for both:
```sh
xyz.onion:50001
-//- :50002
 ```
Wallet is confirmed to work with Tor since I used it for a long time with electrum. Am I missing something in my config files?

**Comment by cculianu** [comment]
I am not sure at all how to use nginx, since I never use it. I just use iptables and/or a traditional firewall on my router.  So.. I wouldn't be the best help as far as nginx goes.  I say this because  I suspect the nginx setup is interfering in some way, since everything else that I **do** understand in what you pasted looks good.

I do think that SSL over Tor might be a problem.  TCP over Tor is the way I have always done it.  Wouldn't you need a separate cert for your tor hostname?

Maybe you should modify the nginx setup to forward the TCP port 50001, not 50002 (SSL)?

Just a thought...

**Comment by DanielPX1** [comment]
Thank you for answer. Already fixed:) 
Also thank you for great work. I see a lot of soul put there

**Comment by diemesleno** [comment]
> Thank you for answer. Already fixed:) Also thank you for great work. I see a lot of soul put there

Hey, could you tell us how did you solve it? 

I'm having the same problem.

I can connect using the IP:50001 but not using tor

I doubled checked my confs and everything looks fine.

For some reason my nginx can't bind the 0.0.0.0:50001
