### ISSUE TITLE
Build Issue on MacOS Apple Silicon: Incompatibility with librocksdb

### ISSUE THREAD

**Issue by pycke** [cculianu/Fulcrum#206]
Hello Calin and Fulcrum Users / Contributors,

I've encountered a build issue while attempting to compile Fulcrum on my Mac Mini with an M2 chip using both Qt Creator IDE and the CLI. It appears that there is an architecture mismatch with the statically-built `librocksdb`, where it's expecting 'arm64' but finding 'x86_64'.

To resolve this, I followed the build instructions in `Fulcrum.pro` to compile new static libraries for `librocksdb` targeting OSX Apple Silicon. Unfortunately, the compilation was unsuccessful with the specified version of `librocksdb` (v6.14.6, commit `ed4316166f67ec892603014634840d29f460f611`). Interestingly, compiling the latest version of `librocksdb` was successful, but integrating the resulting `librocksdb.a` did not allow Fulcrum to compile successfully afterward.

I'm reaching out to inquire if anyone has managed to build Fulcrum on MacOS Apple Silicon successfully and whether there might be more detailed instructions or tips that could assist in this process. Additionally, it would be very helpful if pre-built static binaries for MacOS Apple Silicon could be provided on the Releases page.

Thanks for maintaining and developing this great project !

**Comment by cculianu** [comment]
I would do that but I lack a macOS silicon machine. I actually am on macOS myself but I have been hesitant to switch to their ARM-based processor because I love running Windows binaries via CrossOver and in VMware and am hesitant that stuff will be slower on the newer CPU.

But enough about me -- ok so (1) likely the exact 6.1.4 version of rocksdb doesn't like Apple Silicon.  The latest does and the latest should work ok with Fulcrum.. *provided* you tell Fulcrum where to find the headers for your custom-built rocksdb.

1.  You *need to* install rocksdb after building it, in this case.  Maybe in `/opt/local/` or somesuch.  You may need to reconfigure rocksdb to specify this as the install root... and rebuild.
2. When configuring Fulcrum with Qt IDE, go to the Project setup and edit the Build option for the "Release" configuration, and add the following Build option to the `qmake` line: `LIBS+=/path/to/your/librocksdb.a INCLUDEPATH+=/path/to/your/include/rocksdb`

<img width="910" alt="Screen Shot 2023-11-02 at 9 49 18 AM" src="https://github.com/cculianu/Fulcrum/assets/266627/2d9c0b2f-69c8-4ac8-a286-0b99609955b9">

**Comment by cculianu** [comment]
PS: I think in addition to above `LIBS+=-lrocksdb` should appear on the qmake line to suppress the built-on rocksdb static lib …
