### ISSUE TITLE
Transaction distance from mempool tip is off, shows much closer than it actually is.

### ISSUE THREAD

**Issue by nostitos** [cculianu/Fulcrum#221]
![image](https://github.com/cculianu/Fulcrum/assets/48504624/c4cb7599-5b42-4f8e-af62-137a732a5fa1)

![image](https://github.com/cculianu/Fulcrum/assets/48504624/8bee2691-37a9-4904-8ef6-cb15a9ed2c77)

![image](https://github.com/cculianu/Fulcrum/assets/48504624/70a18ca0-c7c6-438d-8218-9a69161b57df)
Last one is my self hosted Fullcrum

**Comment by cculianu** [comment]
Isn’t this more an issue with electrum wallet?

Also isnt btc mempool particularly chaotic now like aren’t all estimates off because fees are changing constantly?

**Comment by cculianu** [comment]
Also one thing that may be happening: if your btc node just comes up it won’t have an accurate mempool view. It will be missing txns so estimate will be way off.

Is your node always up?

does it’s mempool txn count resemble that of mempool.space ?

**Comment by cculianu** [comment]
Well how many txns are in your mempool vs normal mempools?  Are you doing something like non-standard relay rules or running knots or ordislow or something?

**Comment by nostitos** [comment]
> Well how many txns are in your mempool vs normal mempools? Are you doing something like non-standard relay rules or running knots or ordislow or something?

I'm running the default settings from Parmanode

**Comment by nostitos** [comment]
Do you know of other public fulcrum server I could compare with, 
It's very problematic to estimate fees and confirmation ETA with this issue.

**Comment by cculianu** [comment]
You could use the FulcrumAdmin `peers` command and pick a server.

Or use this website to find one: https://1209k.com/bitcoin-eye/ele.php?chain=btc

**Comment by nostitos** [comment]
Quick survey for a tx at 26sat/b

bitcoins.sk:56002 = 21.52mb Fulcrum
electrum.jochen-hoenicke.de = 21.98MB  Fulcrum
My Fulcrum = 22.12mb (mempool set to 3gb)

electrum.bitaroo.net = 38.57mb  ElectrumX
electrum.emzy.de = 38.62MB electrumX
btc.hodler.ninja:50002 = 39.01mb  ElextrumX

So the discrepancy is between implementation.
(Small variation must be caused by looking up servers few minutes apart.)

Could it be related to byte vs vbytes calculation?

From our experience the ElectrumX calculation is the more correct one. Whenever it's barely below 1mb it's included in next block.

**Comment by cculianu** [comment]
Yeah you may be onto something. Could very well be bytes vs vbytes thing.  Fulcrum was originally written to pretty much ignore segwit stuff. I will look into it. Thanks for doing the investigations.

**Comment by cculianu** [comment]
Yeah you may be onto something. Could very well be bytes vs vbytes thing.  Fulcrum was originally written to pretty much ignore segwit stuff. I will look into it. Thanks for doing the investigations.

**Comment by cculianu** [comment]
I think I have a fix ready -- are you able to build from source and test it? Or shall I prepare a static binary for you? (What platform if so?).

Note that I am travelling and my BTC node just doesn't have a full mempool because it's been offline most of the time and I just fired it up.. but the mempool is mostly empty..  so it's hard to really test, but I can try.

Would appreciate if you can test my fix.

**Comment by cculianu** [comment]
I believe this is fixed in #225. I closed this issue for now but let me know if you want me to send you a binary to test .. I definitely can see now how it was using raw serialized size, rather than vsize, and thus the calculated fees txns were paying were "off" (too low), so you could end up told by Electrum that you are farther ahead in the queue than you really are given the fee calculation electrum was doing for your own txns.

Anyway I believe it's fixed now.

Let me know if you want to test it!  Can send you a binary...

**Comment by cculianu** [comment]
BTW the fix is now live with released version v1.9.8. If you want, you can connect to servers advertising this version (as of the time of this writing that would be: `electrum.jochen-hoenicke.de` port `50006`.

**Comment by nostitos** [comment]
Amazing, thank you so much!
