### ISSUE TITLE
Support running behind a load balancer

### ISSUE THREAD

**Issue by schancel** [cculianu/Fulcrum#29]
There are several headers that need to be supported for banning not to ban the load balancer. Specifically `X-Forward-IP`. Fixing this would allow someone to run a bunch of copies of this under one IP/domain.

**Comment by cculianu** [comment]
I'm not a load balancer guru (read: never used a load balancer). I'm not sure how that relates to banning -- Fulcrum doesn't auto-ban -- it does have per-IP address limits but you can whitelist some addresses (such as the address of your load balancer).

**Comment by cculianu** [comment]
Ok -- You should know that only the WSS port is HTTP -- the regular EC port is.. some custom strange protocol that just sends JSON directly without headers.

So the load balancer support (`X-Forwarded-For`) can be added for WS/WSS only.  I just waned to let you know that I am putting this on my own roadmap (basically a list of things I want to add soon): I will add support for `X-Forwarded-For` (for the WS/WSS ports only -- since they are the only HTTP ports).
