### ISSUE TITLE
Deprecated/removed functions are available outside negotiated version scope.

### ISSUE THREAD

**Issue by monsterbitar** [cculianu/Fulcrum#31]
When I connect to 1.2.5 and 1.2.6 fulcum servers and negotiate protocol version 1.4.1, the `blockchain.address.subscribe` method should not be accessible and I expect to get:

```message: 'unknown method "blockchain.address.subscribe"'```

.. as the `blockchain.address.*` methods were removed in 1.3 and only re-introduced in 1.4.3.

Instead the methods seems to function as if it ignored the version negotiation entirely.

**Comment by cculianu** [comment]
This is not a bug.  There is 0 cost to this.  Don't like the method? Don't call it.

I made a design decision to support all methods.  I do not provide different API "facades" unless they really need to exist.  The only situation in which that is worth doing is if the same method name has different semantics between different APIs.  Since that is not the case here, the method is always presented.
