### ISSUE TITLE
how to get height to use with get_merkle?

### ISSUE THREAD

**Issue by monsterbitar** [cculianu/Fulcrum#66]
I have a transaction hash, which uniquely identifies a transaction. I can make a call to get the transaction hex so I can parse the transaction contents.

In some usecases, such as with `listunspent` and `get_history` I get the block height as part of the call, but what am I expected to do if I start with a transaction, and need to learn if it is included in a block, and if so, get the merkle proof?

( could call `get` with verbose flag on, but that only gives me confirmations - not the actual blockheight)

**Comment by cculianu** [comment]
Yeah it's a problem.  The problem is also the way we index now there's now way to know the height off-hand.  It's definitely annoying.

I will update the  protocol soon to allow the height to be optional.  In which case if you don't specify it, the server will "know". This will balloon the db by about ~4GB or so.  But it will be needed for that `blockchain.transaction.subscribe` method you requested, so given that it's needed there and here, it's justified.

**Comment by monsterbitar** [comment]
Sounds good, and I noticed while reading about changes proposed for electrum you linked to in the other issue that they are also making it optional,so there's clearly some demand for it.

**Comment by cculianu** [comment]
I added `blockchain.transaction.get_height` to 1.4.5. See docs here: https://electrum-cash-protocol.readthedocs.io/en/latest/protocol-changes.html#version-1-4-5

This will be upcoming with the new Fulcrum 1.5.0 release coming soon.
